a = float(input('enter value:'))
b = float(input('enter value:'))
print('#'*50)
print('a is greater than b---> %s' %(a>b))
print('a is less than b ---> %s' %(a<b))
print('a is double equal to b ---> %s' %(a==b))
print('a is not equal to b ---> %s' %(a!=b))
print('a is greater than equal to b ---> %s' %(a>=b))
print('a is less than or equal to b ---> %s' %(a<=b))
print('#'*50)
